seed_everything: 0

checkpoint_path: /host_home/avid_checkpoints/pretrained_base_model/epoch=259-step=260000.ckpt
wandb_group: pretrained_model
wandb_name: pretrained_model
num_batches: 64

data:
  class_path: dwma.lightning.data_modules.procgen_data.ProcgenDataModule
  init_args:
    batch_size: 16
    train_data_folder: /datasets/coinrun_500lvl_train
    test_data_folder: /datasets/coinrun_test
    val_data_folder: /datasets/coinrun_test

trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      save_dir: /host_home/wandb/
      offline: False
      project: avid-eval
      entity: causica
  devices: [0]
  accelerator: "gpu"
