name: act_cond_diffusion_145M
group: act_cond_diffusion_145M
logdir: /host_home/avid

data:
  target: ldwma.lightning.data_modules.rtx.RTXDataModule
  params:
    batch_size: 16
    target_height: 320
    target_width: 512
    dataset_name: "fractal20220817_data"
    shuffle_buffer: 1000
    traj_len: 16
    train_split: "train[:95%]"

model:
  pretrained_checkpoint: /host_home/avid/dynamicrafter_512/model.ckpt # for loading the autoencoder
  only_reload_modules:
    ["first_stage_model", "cond_stage_model", "embedder", "image_proj_model"]
  base_learning_rate: 1e-4
  scale_lr: False
  target: lvdm.models.ddpm3d.LatentVisualDiffusion
  params:
    save_only_unet: True # only save the unet in checkpoint
    linear_warmup_steps: 250
    rescale_betas_zero_snr: True
    parameterization: "v"
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: video
    cond_stage_key: caption
    cond_stage_trainable: False
    image_proj_model_trainable: False
    conditioning_key: hybrid
    image_size: [40, 64]
    channels: 4
    scale_by_std: False
    scale_factor: 0.18215
    use_ema: True
    uncond_prob: 0.05
    uncond_type: "empty_seq"
    rand_cond_frame: false
    use_dynamic_rescale: true
    base_scale: 0.7
    fps_condition_type: "fps"
    perframe_ae: True

    unet_config:
      target: lvdm.modules.networks.openaimodel3d.UNetModel
      params:
        action_conditioned: True
        action_dropout_prob: 0.0
        use_scale_shift_norm: True
        in_channels: 8
        out_channels: 4
        model_channels: 96
        attention_resolutions:
          - 4
          - 2
          - 1
        num_res_blocks: 2
        channel_mult:
          - 1
          - 2
          - 4
          - 4
        dropout: 0.1
        num_head_channels: 64
        transformer_depth: 1
        context_dim: 1024
        use_linear: true
        use_checkpoint: True
        temporal_conv: True
        temporal_attention: True
        temporal_selfatt_only: true
        use_relative_position: false
        use_causal_attention: False
        temporal_length: 16
        addition_attention: true
        image_cross_attention: true
        default_fs: 10
        fs_condition: false

    first_stage_config:
      target: lvdm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
            - 1
            - 2
            - 4
            - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: lvdm.modules.encoders.condition.FrozenOpenCLIPEmbedder
      params:
        freeze: true
        layer: "penultimate"

    img_cond_stage_config:
      target: lvdm.modules.encoders.condition.FrozenOpenCLIPImageEmbedderV2
      params:
        freeze: true

    image_proj_stage_config:
      target: lvdm.modules.encoders.resampler.Resampler
      params:
        dim: 1024
        depth: 4
        dim_head: 64
        heads: 12
        num_queries: 16
        embedding_dim: 1280
        output_dim: 1024
        ff_mult: 4
        video_length: 16

lightning:
  precision: 16
  trainer:
    accelerator: "gpu"
    limit_train_batches: 1000
    limit_val_batches: 50
    check_val_every_n_epoch: 1
    num_nodes: 1
    benchmark: True
    accumulate_grad_batches: 1
    max_steps: 500000
    log_every_n_steps: 10
    gradient_clip_algorithm: "norm"
    gradient_clip_val: 1.0
    logger:
      target: pytorch_lightning.loggers.WandbLogger
      params:
        save_dir: /host_home/wandb/
        offline: False
        project: avid
        entity: causica
        log_model: all
  callbacks:
    model_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        filename: "{epoch}-{step}"
        save_weights_only: True
        every_n_epochs: 5
        save_top_k: -1
    batch_logger:
      target: lvdm.utils.callbacks.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        log_images_kwargs:
          ddim_steps: 50
          unconditional_guidance_scale: 1.0
          timestep_spacing: uniform_trailing
          guidance_rescale: 0.7
          verbose: True
